/**
 * @module
 * Version information for the MCP Client Inspector.
 *
 * This file is auto-generated by scripts/update-version.ts.
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 *
 * Source: deno.jsonc (root)
 * Last updated: 2025-11-03T05:58:58.232Z
 */

/**
 * Current version of the MCP Client Inspector package.
 *
 * This version is synchronized with the version in deno.jsonc and follows
 * semantic versioning (semver) conventions.
 */

/**
 * Current package version
 * @constant
 */
export const VERSION = '0.1.2';

/**
 * Package name
 * @constant
 */
export const PACKAGE_NAME = '@beyondbetter/tools';

/**
 * Full version string with package name
 * @constant
 */
export const FULL_VERSION = `${PACKAGE_NAME}@${VERSION}`;

/**
 * Parse version into major, minor, patch components
 * @returns Object with major, minor, and patch version numbers
 */
export function parseVersion(): {
  major: number;
  minor: number;
  patch: number;
  prerelease?: string;
} {
  const match = VERSION.match(/^(\d+)\.(\d+)\.(\d+)(?:-(.+))?$/);

  if (!match) {
    throw new Error(`Invalid version format: ${VERSION}`);
  }

  return {
    major: parseInt(match[1], 10),
    minor: parseInt(match[2], 10),
    patch: parseInt(match[3], 10),
    prerelease: match[4],
  };
}
